#!/usr/bin/env bash
#
# Records the demo GIFs from demo/tapes/ against the fixture harbour in demo/.
#
# Nothing here reads the machine it runs on. The tapes pass --config demo/
# config.yml, which names only demo/projects, and XDG_DATA_HOME points at a
# registry this script writes, so the store resolves to the checkout rather
# than to whatever the recorder has registered.
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
demo="$root/demo"

for tool in vhs ffmpeg; do
    if ! command -v "$tool" >/dev/null 2>&1; then
        echo "record-demo: $tool is not installed." >&2
        echo "  vhs:    https://github.com/charmbracelet/vhs" >&2
        echo "  ffmpeg: your package manager" >&2
        echo "Neither is in the flake: they are needed to record the demo, not" >&2
        echo "to build or test specgetty." >&2
        exit 1
    fi
done

# The fixture is recorded from a fixed, neutral path rather than from the
# checkout. Two reasons, and the first was found by recording and reading the
# frame: the project header prints the project's absolute path, so recording in
# place published the recorder's home directory and directory layout in every
# GIF. The second falls out of the first: a clone lands wherever the person
# cloning it chose, and a recording made from a fixed path is the same
# recording on every machine.
stage="${SPECGETTY_DEMO_STAGE:-/tmp/specgetty-demo}"
rm -rf "$stage"
mkdir -p "$stage"
cp -R "$demo/projects" "$demo/stores" "$stage/"

# The registry cannot be committed. `local_path` is compared against the store's
# own root, and the store now lives in the staging directory, so the entry is
# written to match wherever that is.
mkdir -p "$stage/data/openspec/stores" "$stage/out"
cp "$demo/config.yml" "$stage/config.yml"
cat > "$stage/data/openspec/stores/registry.yaml" <<REG
# Generated by scripts/record-demo.sh. Not committed: local_path has to be an
# absolute path to wherever the fixture was staged.
stores:
  tideclock:
    backend:
      type: local
      local_path: $stage/stores/tideclock
REG

mkdir -p "$demo/recordings"

# Which version the recordings show. A GIF that no longer matches the interface
# is otherwise indistinguishable from one that does.
cat > "$demo/recordings/RECORDED_AT" <<STAMP
specgetty $(cat "$root/src/VERSION")
$(git -C "$root" rev-parse --short HEAD 2>/dev/null || echo "unknown commit")
STAMP

# A binary built from this checkout, so the recording shows this tree rather
# than whatever spg is on PATH.
go build -o "$stage/spg" ./src

export SPECGETTY_DEMO="$stage"
export XDG_DATA_HOME="$stage/data"
export PATH="$stage:$PATH"

# Resolved to absolute paths before anything changes directory: the tapes are
# run from the staging directory, where a path relative to the checkout means
# nothing.
tapes=()
if [ $# -eq 0 ]; then
    tapes=("$demo"/tapes/*.tape)
else
    for given in "$@"; do
        if [ ! -f "$given" ]; then
            echo "record-demo: no such tape: $given" >&2
            exit 1
        fi
        tapes+=("$(cd "$(dirname "$given")" && pwd)/$(basename "$given")")
    done
fi

for tape in "${tapes[@]}"; do
    echo "==> $(basename "$tape")"
    # Recorded from the staging directory; the Output paths in the tapes are
    # relative, so the GIFs land beside them there and are moved back after.
    ( cd "$stage" && vhs "$tape" )
done

mv "$stage"/out/*.gif "$demo/recordings/" 2>/dev/null || true
echo "==> recorded into demo/recordings, from $(tr '\n' ' ' < "$demo/recordings/RECORDED_AT")"
